onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /tb_rts/u9/rstn
add wave -noupdate /tb_rts/u9/trig_in
add wave -noupdate /tb_rts/u9/orig_sig
add wave -noupdate /tb_rts/u9/tx_data
add wave -noupdate /tb_rts/u9/data_tx_in
add wave -noupdate /tb_rts/u9/u7/temp_data
add wave -noupdate /tb_rts/u9/re_data
add wave -noupdate /tb_rts/u9/re_data_1
add wave -noupdate /tb_rts/u9/re_data_2
add wave -noupdate /tb_rts/u9/re_data_3
add wave -noupdate /tb_rts/u9/re_data_4
add wave -noupdate /tb_rts/u9/wr_data_1
add wave -noupdate /tb_rts/u9/wr_data_2
add wave -noupdate /tb_rts/u9/wr_data_3
add wave -noupdate /tb_rts/u9/wr_data_4
add wave -noupdate /tb_rts/u9/sam_sig_1
add wave -noupdate /tb_rts/u9/sam_sig_2
add wave -noupdate /tb_rts/u9/sam_sig_3
add wave -noupdate /tb_rts/u9/sam_sig_4
add wave -noupdate /tb_rts/u9/done_1
add wave -noupdate /tb_rts/u9/done_2
add wave -noupdate /tb_rts/u9/done_3
add wave -noupdate /tb_rts/u9/done_4
add wave -noupdate /tb_rts/u9/wr_en_1
add wave -noupdate /tb_rts/u9/wr_addr_1
add wave -noupdate /tb_rts/u9/wr_en_2
add wave -noupdate /tb_rts/u9/wr_addr_2
add wave -noupdate /tb_rts/u9/wr_en_3
add wave -noupdate /tb_rts/u9/wr_addr_3
add wave -noupdate /tb_rts/u9/wr_en_4
add wave -noupdate /tb_rts/u9/wr_addr_4
add wave -noupdate /tb_rts/u9/ram_end_1
add wave -noupdate /tb_rts/u9/ram_end_2
add wave -noupdate /tb_rts/u9/ram_end_3
add wave -noupdate /tb_rts/u9/ram_end_4
add wave -noupdate /tb_rts/u9/locked
add wave -noupdate /tb_rts/u9/trig
add wave -noupdate /tb_rts/u9/ram_clk
add wave -noupdate /tb_rts/u9/sam_clk
add wave -noupdate /tb_rts/u9/done
add wave -noupdate /tb_rts/u9/wr_clk
add wave -noupdate /tb_rts/u9/re_addr
add wave -noupdate /tb_rts/u9/start_sig
add wave -noupdate /tb_rts/u9/busy
add wave -noupdate /tb_rts/u9/ram_end
add wave -noupdate /tb_rts/u9/ram_count
add wave -noupdate /tb_rts/u9/all_done_1
add wave -noupdate /tb_rts/u9/all_done_2
add wave -noupdate /tb_rts/u9/all_done_3
add wave -noupdate /tb_rts/u9/all_done_4
add wave -noupdate /tb_rts/u9/re_en
add wave -noupdate /tb_rts/u9/u9/Y1
add wave -noupdate /tb_rts/u9/re_en_1
add wave -noupdate /tb_rts/u9/re_en_2
add wave -noupdate /tb_rts/u9/re_en_3
add wave -noupdate /tb_rts/u9/re_en_4
add wave -noupdate -divider control
add wave -noupdate /tb_rts/u9/u7/rstn
add wave -noupdate /tb_rts/u9/u7/all_done_1
add wave -noupdate /tb_rts/u9/u7/all_done_2
add wave -noupdate /tb_rts/u9/u7/all_done_3
add wave -noupdate /tb_rts/u9/u7/all_done_4
add wave -noupdate /tb_rts/u9/u7/ram_count
add wave -noupdate /tb_rts/u9/u7/re_data
add wave -noupdate /tb_rts/u9/u7/busy
add wave -noupdate /tb_rts/u9/u7/re_en
add wave -noupdate /tb_rts/u9/u7/re_addr
add wave -noupdate /tb_rts/u9/u7/data_uart
add wave -noupdate /tb_rts/u9/u7/start_sig
add wave -noupdate /tb_rts/u9/u7/state
add wave -noupdate /tb_rts/u9/u7/re_cnt
add wave -noupdate /tb_rts/u9/u7/busy_d
add wave -noupdate /tb_rts/u9/u7/flag
add wave -noupdate /tb_rts/u9/u7/flag_busy
add wave -noupdate /tb_rts/u9/u7/count
add wave -noupdate /tb_rts/u9/u7/total_data
add wave -noupdate /tb_rts/u9/u7/all_done
add wave -noupdate /tb_rts/u9/u7/row_addr
add wave -noupdate /tb_rts/u9/u7/temp_ram_count
add wave -noupdate /tb_rts/u9/u7/pclk
add wave -noupdate -divider demux
add wave -noupdate /tb_rts/u9/u9/A
add wave -noupdate /tb_rts/u9/u9/SEL
add wave -noupdate /tb_rts/u9/u9/Y2
add wave -noupdate /tb_rts/u9/u9/Y3
add wave -noupdate /tb_rts/u9/u9/Y4
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {12380000 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 180
configure wave -valuecolwidth 38
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {9742669 ps} {170087725 ps}
